### ISSUE TITLE
Is this an error in util.py?

### ISSUE THREAD

**Issue by zou-xuan** [ml-resources/spark-ml#70]
I am reading the machine learning with Spark book, and in chapter 4, I try to run user_data.py file. However, in the original util.py file there is _from pyspark.sql.types import *_ in function and leads to Syntax error. After I comment these lines I successfully run the code. Is this an error or my mistake? Thanks!

**Comment by rajdeepd** [comment]
Changed location of the import statement, please pull the latest code
